### ISSUE TITLE
🧑‍💼Translation: Translate README.md

### ISSUE THREAD

**Issue by N3v1** [N3v1/SwiftData-ToDo-App#7]
### Hello everyone 👋,
to make this repository available to many people from many countries I could use some help to make the README.md file available in many other languages.

## How to contribiute 
To participate, you must speak at least one language other than English.
If you meet this requirement, I warmly welcome you to translate the README.md into your language.
But please note that the following languages ​​have priority:
- [x] German
- [x] Polish
- [ ] Hindi
- [ ] Italian
- [ ] Spanish
- [ ] Russian
- [ ] Chinese
- [ ] Japanese
- [ ] Korean

**Now let's get down to business:**
1. Fork the repository
2. Clone this repository
3. Create a new branch **(Important: Please note the naming rules)**
4. Create in the translation/ dir a new file named `README_language.md`. **Example:**  `README_de.md`
    ***(Please use for naming the abbreviations of country names )***

### Branch naming rules
- Your username should be at the beginning
- Then separate the username with a ('-') minus sign
- Followed by the language you are translating
**Example:**
*N3v1-german*

### Important note
**⚠️ Please sync your forks to prevent merge conflicts ⚠️**

### Help translate the app
It would help me if you would maybe help translate the app. You can find the link to the issue [**here**](https://github.com/N3v1/To-Do-App/issues/6)

---

Thanks in advance 🙏

**Comment by aakash250798** [comment]
Hi.. why don't u use google translate for this work...
If u need any help then surely I can help...

**Comment by N3v1** [comment]
True, but sometimes the translations from Google Translate are not correct. But thanks for your encouragement 🙏

**Comment by N3v1** [comment]
Sorry to bother you, but what languages ​​do you speak by the way?

**Comment by aakash250798** [comment]
Hindi, English.. does that fit..?

**Comment by N3v1** [comment]
Yes, maybe you can do a Hindi translation. Only if you have the time and inclination. Thanks in advance 🙏

**Comment by aakash250798** [comment]
If Sunday is ok, then ya I can start working from Sunday..

**Comment by N3v1** [comment]
Yes sure

**Comment by N3v1** [comment]
> If Sunday is ok, then ya I can start working from Sunday.

Hi @aakash250798 👋,
How is the progress going with the Hindi translation?

Thank you kindly 🙏
Best regards
NH

**Comment by N3v1** [comment]
###  Hi @aakash250798 👋,
Don't stress. I can understand that. Do it when you have the time and inclination. 
Enjoy the weekend

Thank you kindly 🙏
Best regards
NH

**Comment by N3v1** [comment]
How is it your translation going @aakash250798
